# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class User(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, email: str=None, senha: str=None):  # noqa: E501
        """User - a model defined in Swagger

        :param id: The id of this User.  # noqa: E501
        :type id: int
        :param email: The email of this User.  # noqa: E501
        :type email: str
        :param senha: The senha of this User.  # noqa: E501
        :type senha: str
        """
        self.swagger_types = {
            'id': int,
            'email': str,
            'senha': str
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'senha': 'senha'
        }
        self._id = id
        self._email = email
        self._senha = senha

    @classmethod
    def from_dict(cls, dikt) -> 'User':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The User of this User.  # noqa: E501
        :rtype: User
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this User.

        Código do usuário  # noqa: E501

        :return: The id of this User.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this User.

        Código do usuário  # noqa: E501

        :param id: The id of this User.
        :type id: int
        """

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this User.

        Email do usuário  # noqa: E501

        :return: The email of this User.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this User.

        Email do usuário  # noqa: E501

        :param email: The email of this User.
        :type email: str
        """

        self._email = email

    @property
    def senha(self) -> str:
        """Gets the senha of this User.

        Senha do usuário  # noqa: E501

        :return: The senha of this User.
        :rtype: str
        """
        return self._senha

    @senha.setter
    def senha(self, senha: str):
        """Sets the senha of this User.

        Senha do usuário  # noqa: E501

        :param senha: The senha of this User.
        :type senha: str
        """

        self._senha = senha
